import { render } from "lit";
import { describe, expect, it, vi } from "vitest";
import type { AppViewState } from "../app-view-state.ts";
import type { ThemeMode, ThemeName } from "../theme.ts";
import { renderLoginGate } from "./login-gate.ts";

function createState(overrides: Partial<AppViewState> = {}): AppViewState {
  const settings = {
    gatewayUrl: "ws://127.0.0.1:18789",
    token: "",
    sessionKey: "main",
    lastActiveSessionKey: "main",
    theme: "claw" as ThemeName,
    themeMode: "system" as ThemeMode,
    googleClientId: "client-id.apps.googleusercontent.com",
    googleLoginRequired: true,
    googleProfileEmail: "",
    googleProfileName: "",
    googleProfileAvatar: "",
    emailNotificationsEnabled: true,
    emailNotificationsRecipient: "alerts@example.com",
    chatFocusMode: false,
    chatShowThinking: true,
    chatShowToolCalls: true,
    splitRatio: 0.6,
    navCollapsed: false,
    navWidth: 220,
    navGroupsCollapsed: {},
    borderRadius: 50,
  };

  return {
    settings,
    password: "",
    loginShowGatewayToken: false,
    loginShowGatewayPassword: false,
    googleSignInBusy: false,
    googleLoginError: null,
    tab: "chat",
    onboarding: false,
    basePath: "",
    connected: false,
    theme: "claw",
    themeMode: "system",
    themeResolved: "dark",
    themeOrder: ["claw", "knot", "dash"],
    hello: null,
    lastError: null,
    lastErrorCode: null,
    eventLog: [],
    assistantName: "OpenClaw",
    assistantAvatar: null,
    assistantAgentId: null,
    sessionKey: "main",
    chatLoading: false,
    chatSending: false,
    chatMessage: "",
    chatAttachments: [],
    chatMessages: [],
    chatToolMessages: [],
    chatStreamSegments: [],
    chatStream: null,
    chatStreamStartedAt: null,
    chatRunId: null,
    compactionStatus: null,
    fallbackStatus: null,
    chatAvatarUrl: null,
    chatThinkingLevel: null,
    chatModelOverrides: {},
    chatModelsLoading: false,
    chatModelCatalog: [],
    chatQueue: [],
    chatManualRefreshInFlight: false,
    nodesLoading: false,
    nodes: [],
    chatNewMessagesBelow: false,
    navDrawerOpen: false,
    sidebarOpen: false,
    sidebarContent: null,
    sidebarError: null,
    splitRatio: 0.6,
    scrollToBottom: () => undefined,
    devicesLoading: false,
    devicesError: null,
    devicesList: null,
    execApprovalsLoading: false,
    execApprovalsSaving: false,
    execApprovalsDirty: false,
    execApprovalsSnapshot: null,
    execApprovalsForm: null,
    execApprovalsSelectedAgent: null,
    execApprovalsTarget: "gateway",
    execApprovalsTargetNodeId: null,
    execApprovalQueue: [],
    execApprovalBusy: false,
    execApprovalError: null,
    pendingGatewayUrl: null,
    configLoading: false,
    configRaw: "",
    configRawOriginal: "",
    configValid: null,
    configIssues: [],
    configSaving: false,
    configApplying: false,
    updateRunning: false,
    applySessionKey: "main",
    configSnapshot: null,
    configSchema: null,
    configSchemaVersion: null,
    configSchemaLoading: false,
    configUiHints: {},
    configForm: null,
    configFormOriginal: null,
    configFormMode: "form",
    configSearchQuery: "",
    configActiveSection: null,
    configActiveSubsection: null,
    communicationsFormMode: "form",
    communicationsSearchQuery: "",
    communicationsActiveSection: null,
    communicationsActiveSubsection: null,
    appearanceFormMode: "form",
    appearanceSearchQuery: "",
    appearanceActiveSection: null,
    appearanceActiveSubsection: null,
    automationFormMode: "form",
    automationSearchQuery: "",
    automationActiveSection: null,
    automationActiveSubsection: null,
    infrastructureFormMode: "form",
    infrastructureSearchQuery: "",
    infrastructureActiveSection: null,
    infrastructureActiveSubsection: null,
    aiAgentsFormMode: "form",
    aiAgentsSearchQuery: "",
    aiAgentsActiveSection: null,
    aiAgentsActiveSubsection: null,
    channelsLoading: false,
    channelsSnapshot: null,
    channelsError: null,
    channelsLastSuccess: null,
    whatsappLoginMessage: null,
    whatsappLoginQrDataUrl: null,
    whatsappLoginConnected: null,
    whatsappBusy: false,
    nostrProfileFormState: null,
    nostrProfileAccountId: null,
    configFormDirty: false,
    presenceLoading: false,
    presenceEntries: [],
    presenceError: null,
    presenceStatus: null,
    agentsLoading: false,
    agentsList: null,
    agentsError: null,
    agentsSelectedId: null,
    toolsCatalogLoading: false,
    toolsCatalogError: null,
    toolsCatalogResult: null,
    agentsPanel: "overview",
    agentFilesLoading: false,
    agentFilesError: null,
    agentFilesList: null,
    agentFileContents: {},
    agentFileDrafts: {},
    agentFileActive: null,
    agentFileSaving: false,
    agentIdentityLoading: false,
    agentIdentityError: null,
    agentIdentityById: {},
    agentSkillsLoading: false,
    agentSkillsError: null,
    agentSkillsReport: null,
    agentSkillsAgentId: null,
    sessionsLoading: false,
    sessionsResult: null,
    sessionsError: null,
    sessionsFilterActive: "",
    sessionsFilterLimit: "",
    sessionsIncludeGlobal: false,
    sessionsIncludeUnknown: false,
    sessionsHideCron: false,
    sessionsSearchQuery: "",
    sessionsSortColumn: "updated",
    sessionsSortDir: "desc",
    sessionsPage: 0,
    sessionsPageSize: 10,
    sessionsActionsOpenKey: null,
    usageLoading: false,
    usageResult: null,
    usageCostSummary: null,
    usageError: null,
    usageStartDate: "",
    usageEndDate: "",
    usageSelectedSessions: [],
    usageSelectedDays: [],
    usageSelectedHours: [],
    usageChartMode: "tokens",
    usageDailyChartMode: "total",
    usageTimeSeriesMode: "cumulative",
    usageTimeSeriesBreakdownMode: "total",
    usageTimeSeries: null,
    usageTimeSeriesLoading: false,
    usageTimeSeriesCursorStart: null,
    usageTimeSeriesCursorEnd: null,
    usageSessionLogs: null,
    usageSessionLogsLoading: false,
    usageSessionLogsExpanded: false,
    usageQuery: "",
    usageQueryDraft: "",
    usageQueryDebounceTimer: null,
    usageSessionSort: "tokens",
    usageSessionSortDir: "desc",
    usageRecentSessions: [],
    usageTimeZone: "local",
    usageContextExpanded: false,
    usageHeaderPinned: false,
    usageSessionsTab: "all",
    usageVisibleColumns: [],
    usageLogFilterRoles: [],
    usageLogFilterTools: [],
    usageLogFilterHasTools: false,
    usageLogFilterQuery: "",
    cronLoading: false,
    cronJobsLoadingMore: false,
    cronJobs: [],
    cronJobsTotal: 0,
    cronJobsHasMore: false,
    cronJobsNextOffset: 0,
    cronJobsLimit: 0,
    cronJobsQuery: "",
    cronJobsEnabledFilter: "all",
    cronJobsSort: "updatedAt",
    cronJobsSortDir: "desc",
    cronRunsLoading: false,
    cronRuns: [],
    cronRunsHasMore: false,
    cronRunsNextCursor: null,
    cronRunsSelectedJobId: null,
    cronRunsQuery: "",
    cronRunsSortDir: "desc",
    cronRunsScope: "all",
    cronForm: null,
    cronFormDirty: false,
    cronFormSaving: false,
    cronFormError: null,
    cronFormMode: "create",
    cronModelSuggestions: null,
    cronStatus: null,
    cronStatusError: null,
    debugConnected: false,
    debugHeartbeat: null,
    debugCallMethod: "",
    debugCallParams: "",
    debugCallResult: null,
    debugCallError: null,
    logsLoading: false,
    logsError: null,
    logsFile: null,
    logsEntries: [],
    logsFilterText: "",
    logsLevelFilters: {
      trace: true,
      debug: true,
      info: true,
      warn: true,
      error: true,
      fatal: true,
    },
    logsAutoFollow: false,
    logsTruncated: false,
    logsCursor: null,
    logsLastFetchAt: null,
    logsLimit: 200,
    logsMaxBytes: 0,
    logsAtBottom: true,
    updateAvailable: null,
    attentionItems: [],
    paletteOpen: false,
    paletteQuery: "",
    paletteActiveIndex: 0,
    streamMode: false,
    overviewShowGatewayToken: false,
    overviewShowGatewayPassword: false,
    overviewLogLines: [],
    overviewLogCursor: 0,
    client: null,
    refreshSessionsAfterChat: new Set(),
    connect: vi.fn(),
    startGoogleLogin: vi.fn(async () => undefined),
    signOutGoogleLogin: vi.fn(),
    draftNotificationEmail: vi.fn(),
    sendTestNotificationEmail: vi.fn(),
    setTab: vi.fn(),
    setTheme: vi.fn(),
    setThemeMode: vi.fn(),
    setBorderRadius: vi.fn(),
    applySettings: vi.fn(),
    loadOverview: vi.fn(async () => undefined),
    loadAssistantIdentity: vi.fn(async () => undefined),
    loadCron: vi.fn(async () => undefined),
    handleWhatsAppStart: vi.fn(async () => undefined),
    handleWhatsAppWait: vi.fn(async () => undefined),
    handleWhatsAppLogout: vi.fn(async () => undefined),
    handleChannelConfigSave: vi.fn(async () => undefined),
    handleChannelConfigReload: vi.fn(async () => undefined),
    handleNostrProfileEdit: vi.fn(),
    handleNostrProfileCancel: vi.fn(),
    handleNostrProfileFieldChange: vi.fn(),
    handleNostrProfileSave: vi.fn(async () => undefined),
    handleNostrProfileImport: vi.fn(async () => undefined),
    handleNostrProfileToggleAdvanced: vi.fn(),
    handleExecApprovalDecision: vi.fn(async () => undefined),
    handleGatewayUrlConfirm: vi.fn(),
    handleGatewayUrlCancel: vi.fn(),
    handleConfigLoad: vi.fn(async () => undefined),
    handleConfigSave: vi.fn(async () => undefined),
    handleConfigApply: vi.fn(async () => undefined),
    handleConfigFormUpdate: vi.fn(),
    handleConfigFormModeChange: vi.fn(),
    handleConfigRawChange: vi.fn(),
    handleInstallSkill: vi.fn(async () => undefined),
    handleUpdateSkill: vi.fn(async () => undefined),
    handleAgentSelection: vi.fn(),
    handleAgentPanelChange: vi.fn(),
    handleAgentFileSelect: vi.fn(),
    handleAgentFileChange: vi.fn(),
    handleAgentFileSave: vi.fn(async () => undefined),
    handleSessionsLoad: vi.fn(async () => undefined),
    handleSessionPatch: vi.fn(async () => undefined),
    handleSessionDelete: vi.fn(async () => undefined),
    handleNavigateToChatSession: vi.fn(),
    handleUsageLoad: vi.fn(async () => undefined),
    handleChatModelChange: vi.fn(),
    handleChatThinkingLevelChange: vi.fn(),
    handleChatRefresh: vi.fn(async () => undefined),
    handleToggleFocusMode: vi.fn(),
    handleChatDraftChange: vi.fn(),
    handleSendChat: vi.fn(async () => undefined),
    handleRemoveChatQueueItem: vi.fn(),
    handleNewChatSession: vi.fn(),
    handleExportLogs: vi.fn(),
    handleLogLevelToggle: vi.fn(),
    handleLogsFilterTextChange: vi.fn(),
    handleLogsRefresh: vi.fn(async () => undefined),
    handleDebugCall: vi.fn(async () => undefined),
    handleScrollToBottom: vi.fn(),
    handleOpenSidebar: vi.fn(),
    handleCloseSidebar: vi.fn(),
    exportLogs: vi.fn(),
    handleChatScroll: vi.fn(),
    handleLogsScroll: vi.fn(),
    resetToolStream: vi.fn(),
    resetChatScroll: vi.fn(),
    removeQueuedMessage: vi.fn(),
    setLocale: vi.fn(async () => undefined),
    ...overrides,
  } as unknown as AppViewState;
}

describe("login gate", () => {
  it("locks the gateway connect button until Google sign-in completes", async () => {
    const container = document.createElement("div");
    render(renderLoginGate(createState()), container);
    await Promise.resolve();

    const connectButton = Array.from(container.querySelectorAll("button")).find((button) =>
      button.textContent?.includes("Continue with Google first"),
    );
    expect(connectButton).toBeTruthy();
    expect(connectButton?.disabled).toBe(true);
  });

  it("shows the active Google profile when one is stored", async () => {
    const container = document.createElement("div");
    render(
      renderLoginGate(
        createState({
          settings: {
            ...createState().settings,
            googleProfileEmail: "person@example.com",
            googleProfileName: "Person Example",
          },
        }),
      ),
      container,
    );
    await Promise.resolve();

    expect(container.textContent).toContain("person@example.com");
    expect(container.textContent).toContain("Person Example");
  });
});
